package com.neuedu.dao;

import com.neuedu.pojo.Category;
import com.neuedu.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);


    List<Category> findAllCategoryMessage();

    List<Product> findProlimit(@Param("offset") int offset, @Param("pagesize") int pagesize);

    int findRecords();

    //上下架
    int upordeleteproduct(@Param(("id")) int pruductid,@Param(("status")) int status);

    //去别的表查询pid
    int findthispid(int parentId);

    //查询商品通过名字模糊查询或者id准确查询
    List<Product> findproductBynameOrid(@Param("productName")String productName,@Param("productId")Integer productId);

    List<Product> searchproductsbyidandkeyword(@Param("integerList") List<Integer> integerList,
                                               @Param("keyword")String keyword);
}