package com.neuedu.dao;

import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserInfo record);
    UserInfo findByUsernameAndPassword(@Param("user") UserInfo userInfo);

    int exsitsUsername(@Param("username") String username);
    int exsitsEmail(@Param("email") String email);
    String findquestionbyusername(String username);
    int findexsitsquestionByusername(String username);
    String exsitsAnswerByusernameAndquestion(@Param("username") String username,@Param("question") String question);
    int outUpdatePasswordByUsername(@Param("username")String username,@Param("newpassword")String newpassword);
    int inUpdatePasswordByOldpassword(@Param("username")String username,@Param("newpassword")String newpassword);
    int InUpdateUserMessageByUsername(@Param("email")String email,
                                      @Param("phone")String phone,
                                      @Param("question")String question,
                                      @Param("answer")String answer,
                                      @Param("username")String username);

    UserInfo findUserByusername(String username);


}